### ISSUE TITLE
Example protein simulation does not work properly

### ISSUE THREAD

**Issue by axsk** [JuliaMolSim/Molly.jl#38] opened 2021-05-12 14:12 UTC
I tried running the example code for the protein.

After a copy and paste of the code (fixing the `neighbor` -> `neighbour` typo) and loading the result into VMD I was surprised seeing the atoms jumping around like crazy.

Indeed a look at the temperature logger confirmed that the temperature raised from `260` to `6000` K after the first 500 steps.

**Comment by jgreener64** [comment] 2021-05-12 14:20
Okay I'll have a look at this.

The `neighbor`/`neighbour` thing is due to a difference on master v the release version rather than a typo, it will be `neighbor` permanently after the next release.

**Comment by jgreener64** [comment] 2021-05-19 18:27
The explosion was caused by a mistake in sparse vector construction and is fixed in v0.3.0.

There are still some issues affecting the stability of the peptide such as weighting the 1-4 non-bonded terms and long-range electrostatics. Those are being worked on elsewhere.

Thanks for reporting this.

**Closed by jgreener64** 2021-05-19 18:27 UTC
